import type { Page as PlaywrightPageType } from "@playwright/test";
import type { BrowserContext } from "@commands/context/types";
import type { FrameLocator } from "@commands/frame/types";
import type { Page as PageClassType } from "./page";
import type { component } from "./command/component";
import type { dialogListener } from "./command/dialog-listener";
import type { downloadFile } from "./command/download-file";
import type { expect } from "./command/expect";
import type { frameLocator } from "./command/frame-locator";
import type { getByAltText } from "./command/get-by-alt-text";
import type { getByLabel } from "./command/get-by-label";
import type { getByPlaceholder } from "./command/get-by-placeholder";
import type { getByRole } from "./command/get-by-role";
import type { getByTestId } from "./command/get-by-test-id";
import type { getByText } from "./command/get-by-text";
import type { getByTitle } from "./command/get-by-title";
import type { given } from "./command/given";
import type { locator } from "./command/locator";
import type { requestsInterceptor } from "./command/requests-interceptor";
import type { scrollTo } from "./command/scroll-to";
import type { scrollToBottom } from "./command/scroll-to-bottom";
import type { scrollToTop } from "./command/scroll-to-top";
import type { switchToFrame } from "./command/switch-to-frame";
import type { urlFromBase } from "./command/url-from-base";

export interface Page extends PlaywrightPageType, PageClassType {
  context: () => BrowserContext;
  activeframe: FrameLocator;
  dialog: { handled: boolean, message: string };
  component<T>(...args: Parameters<typeof component<T>>): ReturnType<typeof component<T>>;
  dialogListener(...args: Parameters<typeof dialogListener>): ReturnType<typeof dialogListener>;
  downloadFile(...args: Parameters<typeof downloadFile>): ReturnType<typeof downloadFile>;
  expect(...args: Parameters<typeof expect>): ReturnType<typeof expect>;
  frameLocator(...args: Parameters<PlaywrightPageType["frameLocator"]>): ReturnType<typeof frameLocator>;
  getByAltText(...args: Parameters<typeof getByAltText>): ReturnType<typeof getByAltText>;
  getByLabel(...args: Parameters<typeof getByLabel>): ReturnType<typeof getByLabel>;
  getByPlaceholder(...args: Parameters<typeof getByPlaceholder>): ReturnType<typeof getByPlaceholder>;
  getByRole(...args: Parameters<typeof getByRole>): ReturnType<typeof getByRole>;
  getByTestId(...args: Parameters<typeof getByTestId>): ReturnType<typeof getByTestId>;
  getByText(...args: Parameters<typeof getByText>): ReturnType<typeof getByText>;
  getByTitle(...args: Parameters<typeof getByTitle>): ReturnType<typeof getByTitle>;
  given(...args: Parameters<typeof given>): ReturnType<typeof given>;
  locator(...args: Parameters<typeof locator>): ReturnType<typeof locator>;
  requestsInterceptor(...args: Parameters<typeof requestsInterceptor>): ReturnType<typeof requestsInterceptor>;
  scrollTo(...args: Parameters<typeof scrollTo>): ReturnType<typeof scrollTo>;
  scrollToBottom(...args: Parameters<typeof scrollToBottom>): ReturnType<typeof scrollToBottom>;
  scrollToTop(...args: Parameters<typeof scrollToTop>): ReturnType<typeof scrollToTop>;
  switchToFrame(...args: Parameters<typeof switchToFrame>): ReturnType<typeof switchToFrame>;
  urlFromBase(...args: Parameters<typeof urlFromBase>): ReturnType<typeof urlFromBase>;
}
