import type { Locator as PlaywrightLocatorType } from "@playwright/test";
import type { Page } from "@commands/page/types";
import type { Locator as LocatorClassType } from "./locator";
import type { all } from "./command/all";
import type { and } from "./command/and";
import type { centerPoint } from "./command/center-point";
import type { clickUntil } from "./command/click-until";
import type { doUntil } from "./command/do-until";
import type { dragAndDrop } from "./command/drag-and-drop";
import type { dropdownOptions } from "./command/dropdown-options";
import type { expect } from "./command/expect";
import type { fill } from "./command/fill";
import type { first } from "./command/first";
import type { getByAltText } from "./command/get-by-alt-text";
import type { getByLabel } from "./command/get-by-label";
import type { getByPlaceholder } from "./command/get-by-placeholder";
import type { getByRole } from "./command/get-by-role";
import type { getByTestId } from "./command/get-by-test-id";
import type { getByText } from "./command/get-by-text";
import type { getByTitle } from "./command/get-by-title";
import type { given } from "./command/given";
import type { hoverIntoView } from "./command/hover-into-view";
import type { isFocused } from "./command/is-focused";
import type { isSelected } from "./command/is-selected";
import type { last } from "./command/last";
import type { location } from "./command/location";
import type { locator } from "./command/locator";
import type { nth } from "./command/nth";
import type { or } from "./command/or";
import type { press } from "./command/press";
import type { scrollIntoView } from "./command/scroll-into-view";
import type { selectOption } from "./command/select-option";
import type { uploadFiles } from "./command/upload-files";

// @ts-ignore
export interface Locator extends PlaywrightLocatorType, LocatorClassType {
  _selector: string;
  all: typeof all;
  and: typeof and;
  centerPoint: typeof centerPoint;
  clickUntil: typeof clickUntil;
  doUntil: typeof doUntil;
  dragAndDrop: typeof dragAndDrop;
  dropdownOptions: typeof dropdownOptions;
  expect: typeof expect;
  fill: typeof fill;
  first: typeof first;
  getByAltText: typeof getByAltText;
  getByLabel: typeof getByLabel;
  getByPlaceholder: typeof getByPlaceholder;
  getByRole: typeof getByRole;
  getByTestId: typeof getByTestId;
  getByText: typeof getByText;
  getByTitle: typeof getByTitle;
  given: typeof given;
  hoverIntoView: typeof hoverIntoView;
  isFocused: typeof isFocused;
  isSelected: typeof isSelected;
  last: typeof last;
  location: typeof location;
  locator: typeof locator;
  page: () => Page;
  nth: typeof nth;
  or: typeof or;
  press: typeof press;
  scrollIntoView: typeof scrollIntoView;
  selectOption: typeof selectOption;
  uploadFiles: typeof uploadFiles;
}
